/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from '@payloadcms/db-postgres'
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  varchar,
  timestamp,
  serial,
  numeric,
  boolean,
  text,
  jsonb,
  pgEnum,
} from '@payloadcms/db-postgres/drizzle/pg-core'
import { sql, relations } from '@payloadcms/db-postgres/drizzle'
export const enum_users_role = pgEnum('enum_users_role', ['admin', 'moderator', 'custom'])
export const enum_df_pages_blocks_df_media_type = pgEnum('enum_df_pages_blocks_df_media_type', [
  'image',
  'video',
])
export const enum_projects_website = pgEnum('enum_projects_website', [
  'None',
  'Archia',
  'Magnum Projects',
  'DF',
  'All',
])
export const enum_publications_website = pgEnum('enum_publications_website', [
  'None',
  'Archia',
  'Magnum Projects',
  'DF',
  'All',
])

export const users_sessions = pgTable(
  'users_sessions',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 }),
    expiresAt: timestamp('expires_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index('users_sessions_order_idx').on(columns._order),
    index('users_sessions_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [users.id],
      name: 'users_sessions_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const users = pgTable(
  'users',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    role: enum_users_role('role').notNull().default('admin'),
    customType: integer('custom_type_id').references(() => user_types.id, {
      onDelete: 'set null',
    }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    email: varchar('email').notNull(),
    resetPasswordToken: varchar('reset_password_token'),
    resetPasswordExpiration: timestamp('reset_password_expiration', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar('salt'),
    hash: varchar('hash'),
    resetPasswordRequestedAt: timestamp('reset_password_requested_at', {
      mode: 'string',
      withTimezone: true,
      precision: 3,
    }),
    loginAttempts: numeric('login_attempts', { mode: 'number' }).default(0),
    lockUntil: timestamp('lock_until', { mode: 'string', withTimezone: true, precision: 3 }),
  },
  (columns) => [
    index('users_custom_type_idx').on(columns.customType),
    index('users_updated_at_idx').on(columns.updatedAt),
    index('users_created_at_idx').on(columns.createdAt),
    uniqueIndex('users_email_idx').on(columns.email),
  ],
)

export const user_types = pgTable(
  'user_types',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    permissions_managePages: boolean('permissions_manage_pages').default(true),
    permissions_manageProjects: boolean('permissions_manage_projects').default(true),
    permissions_managePublications: boolean('permissions_manage_publications').default(true),
    permissions_manageMedia: boolean('permissions_manage_media').default(true),
    permissions_manageStudio: boolean('permissions_manage_studio').default(false),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('user_types_slug_idx').on(columns.slug),
    index('user_types_updated_at_idx').on(columns.updatedAt),
    index('user_types_created_at_idx').on(columns.createdAt),
  ],
)

export const media = pgTable(
  'media',
  {
    id: serial('id').primaryKey(),
    alt: varchar('alt').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    url: varchar('url'),
    thumbnailURL: varchar('thumbnail_u_r_l'),
    filename: varchar('filename'),
    mimeType: varchar('mime_type'),
    filesize: numeric('filesize', { mode: 'number' }),
    width: numeric('width', { mode: 'number' }),
    height: numeric('height', { mode: 'number' }),
    focalX: numeric('focal_x', { mode: 'number' }),
    focalY: numeric('focal_y', { mode: 'number' }),
  },
  (columns) => [
    index('media_updated_at_idx').on(columns.updatedAt),
    index('media_created_at_idx').on(columns.createdAt),
    uniqueIndex('media_filename_idx').on(columns.filename),
  ],
)

export const pages_blocks_home_hero_video_urls = pgTable(
  'pages_blocks_home_hero_video_urls',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    url: varchar('url').notNull().default('/videos/2.mp4'),
  },
  (columns) => [
    index('pages_blocks_home_hero_video_urls_order_idx').on(columns._order),
    index('pages_blocks_home_hero_video_urls_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_home_hero.id],
      name: 'pages_blocks_home_hero_video_urls_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_home_hero = pgTable(
  'pages_blocks_home_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    headline: varchar('headline').default('ARCHIA'),
    subtitle: varchar('subtitle').default('Multidisciplinary Architecture & Interiors • London'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_home_hero_order_idx').on(columns._order),
    index('pages_blocks_home_hero_parent_id_idx').on(columns._parentID),
    index('pages_blocks_home_hero_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_home_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_featured_projects = pgTable(
  'pages_blocks_featured_projects',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag').default('02 / Architectural Commissions'),
    title: varchar('title').default('Selected Works'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_featured_projects_order_idx').on(columns._order),
    index('pages_blocks_featured_projects_parent_id_idx').on(columns._parentID),
    index('pages_blocks_featured_projects_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_featured_projects_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_projects_archive = pgTable(
  'pages_blocks_projects_archive',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('All Works'),
    description: varchar('description').default(
      'An international portfolio of multidisciplinary commissions across London, Baku, Dubai, and beyond. Our work spans landmark sports infrastructure, commercial flagships, and bespoke high-end residences. Explore our complete archive of built projects, urban masterplans, and ongoing developments.',
    ),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_projects_archive_order_idx').on(columns._order),
    index('pages_blocks_projects_archive_parent_id_idx').on(columns._parentID),
    index('pages_blocks_projects_archive_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_projects_archive_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_studio_intro = pgTable(
  'pages_blocks_studio_intro',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('Studio'),
    badge: varchar('badge').default('London Practice'),
    description: varchar('description').default(
      'We are a multidisciplinary design studio delivering unique architectural commissions of any scale. Our works range from bespoke residential architecture, commercial interiors, and sports infrastructure to urban masterplanning.',
    ),
    heroImage: integer('hero_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_studio_intro_order_idx').on(columns._order),
    index('pages_blocks_studio_intro_parent_id_idx').on(columns._parentID),
    index('pages_blocks_studio_intro_path_idx').on(columns._path),
    index('pages_blocks_studio_intro_hero_image_idx').on(columns.heroImage),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_studio_intro_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_founder_profile = pgTable(
  'pages_blocks_founder_profile',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    name: varchar('name').default('Davud Farzulla'),
    role: varchar('role').default('Founder & RIBA Chartered Architect'),
    portrait: integer('portrait_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    portraitCaption: varchar('portrait_caption').default('Davud Farzulla — Founder & Principal'),
    bio: varchar('bio').default(
      'Davud Farzulla is a RIBA Chartered Architect and Interior Designer with over 20 years’ experience in the UK construction industry. In 2020, Davud founded Archia to provide a fully integrated design and management service tailored specifically to private clients.',
    ),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_founder_profile_order_idx').on(columns._order),
    index('pages_blocks_founder_profile_parent_id_idx').on(columns._parentID),
    index('pages_blocks_founder_profile_path_idx').on(columns._path),
    index('pages_blocks_founder_profile_portrait_idx').on(columns.portrait),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_founder_profile_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_about_section = pgTable(
  'pages_blocks_about_section',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('About us'),
    description: varchar('description').default(
      'Our experienced team brings together strong design expertise with extensive project management experience across commercial and high-end residential sectors. This combined knowledge allows us to approach each project with both creative clarity and technical precision.',
    ),
    subtext: varchar('subtext').default(
      'We work closely with a trusted network of consultants, specialists, and suppliers, drawing on a well-established supply chain to ensure the highest standards of quality at every stage. Through collaboration, coordination, and attention to detail, we deliver well-resolved spaces that meet the practical, aesthetic, and long-term requirements of each project.',
    ),
    ctaLabel: varchar('cta_label').default('Learn more'),
    ctaLink: varchar('cta_link').default('/contact'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_about_section_order_idx').on(columns._order),
    index('pages_blocks_about_section_parent_id_idx').on(columns._parentID),
    index('pages_blocks_about_section_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_about_section_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_studio_pillars_pillars = pgTable(
  'pages_blocks_studio_pillars_pillars',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    number: varchar('number').default('01 / Architecture'),
    title: varchar('title').default('Residential & Masterplanning'),
    description: varchar('description'),
  },
  (columns) => [
    index('pages_blocks_studio_pillars_pillars_order_idx').on(columns._order),
    index('pages_blocks_studio_pillars_pillars_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_studio_pillars.id],
      name: 'pages_blocks_studio_pillars_pillars_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_studio_pillars = pgTable(
  'pages_blocks_studio_pillars',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_studio_pillars_order_idx').on(columns._order),
    index('pages_blocks_studio_pillars_parent_id_idx').on(columns._parentID),
    index('pages_blocks_studio_pillars_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_studio_pillars_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_journal_feed = pgTable(
  'pages_blocks_journal_feed',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag').default('04 / Insights & Essays'),
    title: varchar('title').default('Journal'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_journal_feed_order_idx').on(columns._order),
    index('pages_blocks_journal_feed_parent_id_idx').on(columns._parentID),
    index('pages_blocks_journal_feed_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_journal_feed_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_journal_archive = pgTable(
  'pages_blocks_journal_archive',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('Publications'),
    description: varchar('description').default(
      'Architectural essays, technical engineering breakdowns, and design philosophies curated by Archia’s London studio.',
    ),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_journal_archive_order_idx').on(columns._order),
    index('pages_blocks_journal_archive_parent_id_idx').on(columns._parentID),
    index('pages_blocks_journal_archive_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_journal_archive_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_contact_hero = pgTable(
  'pages_blocks_contact_hero',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    title: varchar('title').default('Start a Conversation'),
    description: varchar('description').default(
      'ARCHIA collaborates with private clients, visionary developers, and cultural institutions globally. We approach each commission with architectural rigor, bespoke craftsmanship, and an unwavering commitment to enduring quality.',
    ),
    email: varchar('email').default('info@archia.com'),
    statusText: varchar('status_text').default('London Practice • Available for commissions'),
    mapLink: varchar('map_link').default(
      'https://maps.google.com/?q=167-169+Great+Portland+Street+London+W1W+5PF',
    ),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_contact_hero_order_idx').on(columns._order),
    index('pages_blocks_contact_hero_parent_id_idx').on(columns._parentID),
    index('pages_blocks_contact_hero_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_contact_hero_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_contact_locations_locations = pgTable(
  'pages_blocks_contact_locations_locations',
  {
    _order: integer('_order').notNull(),
    _parentID: varchar('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag').default('01 / Practice Headquarters'),
    studioName: varchar('studio_name').default('London Studio'),
    address: varchar('address').default(
      'ARCHIA Studio\n167–169 Great Portland Street\n5th Floor, Fitzrovia\nLondon W1W 5PF\nUnited Kingdom',
    ),
    hours: varchar('hours').default('Monday – Friday, 09:00 – 18:00 GMT'),
    transit: varchar('transit').default("Great Portland St • Oxford Circus • Regent's Park"),
    mapUrl: varchar('map_url').default(
      'https://maps.google.com/?q=167-169+Great+Portland+Street+London+W1W+5PF',
    ),
  },
  (columns) => [
    index('pages_blocks_contact_locations_locations_order_idx').on(columns._order),
    index('pages_blocks_contact_locations_locations_parent_id_idx').on(columns._parentID),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages_blocks_contact_locations.id],
      name: 'pages_blocks_contact_locations_locations_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_contact_locations = pgTable(
  'pages_blocks_contact_locations',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_contact_locations_order_idx').on(columns._order),
    index('pages_blocks_contact_locations_parent_id_idx').on(columns._parentID),
    index('pages_blocks_contact_locations_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_contact_locations_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_full_width_media = pgTable(
  'pages_blocks_full_width_media',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    caption: varchar('caption').default('Archia Architectural Studio Environment'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_full_width_media_order_idx').on(columns._order),
    index('pages_blocks_full_width_media_parent_id_idx').on(columns._parentID),
    index('pages_blocks_full_width_media_path_idx').on(columns._path),
    index('pages_blocks_full_width_media_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_full_width_media_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages_blocks_content_block = pgTable(
  'pages_blocks_content_block',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    richText: jsonb('rich_text'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('pages_blocks_content_block_order_idx').on(columns._order),
    index('pages_blocks_content_block_parent_id_idx').on(columns._parentID),
    index('pages_blocks_content_block_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [pages.id],
      name: 'pages_blocks_content_block_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const pages = pgTable(
  'pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('pages_slug_idx').on(columns.slug),
    index('pages_updated_at_idx').on(columns.updatedAt),
    index('pages_created_at_idx').on(columns.createdAt),
  ],
)

export const pages_rels = pgTable(
  'pages_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    projectsID: integer('projects_id'),
    publicationsID: integer('publications_id'),
  },
  (columns) => [
    index('pages_rels_order_idx').on(columns.order),
    index('pages_rels_parent_idx').on(columns.parent),
    index('pages_rels_path_idx').on(columns.path),
    index('pages_rels_projects_id_idx').on(columns.projectsID),
    index('pages_rels_publications_id_idx').on(columns.publicationsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [pages.id],
      name: 'pages_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'pages_rels_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['publicationsID']],
      foreignColumns: [publications.id],
      name: 'pages_rels_publications_fk',
    }).onDelete('cascade'),
  ],
)

export const df_pages_blocks_df_biography = pgTable(
  'df_pages_blocks_df_biography',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    eyebrow: varchar('eyebrow').default('FOUNDER & PRINCIPAL ARCHITECT'),
    quote: varchar('quote').default(
      'Architecture begins with attentive listening. We translate each client distinct rhythm of life into structures of timeless proportion, warmth, and permanence.',
    ),
    bio: jsonb('bio'),
    portrait: integer('portrait_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('df_pages_blocks_df_biography_order_idx').on(columns._order),
    index('df_pages_blocks_df_biography_parent_id_idx').on(columns._parentID),
    index('df_pages_blocks_df_biography_path_idx').on(columns._path),
    index('df_pages_blocks_df_biography_portrait_idx').on(columns.portrait),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [df_pages.id],
      name: 'df_pages_blocks_df_biography_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const df_pages_blocks_df_projects = pgTable(
  'df_pages_blocks_df_projects',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    tag: varchar('tag').default('01 / ARCHITECTURAL COMMISSIONS'),
    title: varchar('title').default('Selected Commissions'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('df_pages_blocks_df_projects_order_idx').on(columns._order),
    index('df_pages_blocks_df_projects_parent_id_idx').on(columns._parentID),
    index('df_pages_blocks_df_projects_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [df_pages.id],
      name: 'df_pages_blocks_df_projects_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const df_pages_blocks_df_media = pgTable(
  'df_pages_blocks_df_media',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    type: enum_df_pages_blocks_df_media_type('type').default('image'),
    image: integer('image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    videoUrl: varchar('video_url'),
    caption: varchar('caption').default('Architectural Composition & Material Permanence'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('df_pages_blocks_df_media_order_idx').on(columns._order),
    index('df_pages_blocks_df_media_parent_id_idx').on(columns._parentID),
    index('df_pages_blocks_df_media_path_idx').on(columns._path),
    index('df_pages_blocks_df_media_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [df_pages.id],
      name: 'df_pages_blocks_df_media_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const df_pages_blocks_df_content = pgTable(
  'df_pages_blocks_df_content',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    richText: jsonb('rich_text'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('df_pages_blocks_df_content_order_idx').on(columns._order),
    index('df_pages_blocks_df_content_parent_id_idx').on(columns._parentID),
    index('df_pages_blocks_df_content_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [df_pages.id],
      name: 'df_pages_blocks_df_content_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const df_pages_blocks_df_contact = pgTable(
  'df_pages_blocks_df_contact',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    _path: text('_path').notNull(),
    id: varchar('id').primaryKey(),
    headline: varchar('headline').default('Private Commission Briefing'),
    email: varchar('email').default('davud@archia.com'),
    phone: varchar('phone').default('+44 (0) 20 7946 0928'),
    office: varchar('office').default('Fitzrovia, Central London'),
    blockName: varchar('block_name'),
  },
  (columns) => [
    index('df_pages_blocks_df_contact_order_idx').on(columns._order),
    index('df_pages_blocks_df_contact_parent_id_idx').on(columns._parentID),
    index('df_pages_blocks_df_contact_path_idx').on(columns._path),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [df_pages.id],
      name: 'df_pages_blocks_df_contact_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const df_pages = pgTable(
  'df_pages',
  {
    id: serial('id').primaryKey(),
    title: varchar('title').notNull(),
    slug: varchar('slug').notNull(),
    subtitle: varchar('subtitle'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('df_pages_slug_idx').on(columns.slug),
    index('df_pages_updated_at_idx').on(columns.updatedAt),
    index('df_pages_created_at_idx').on(columns.createdAt),
  ],
)

export const df_pages_rels = pgTable(
  'df_pages_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    projectsID: integer('projects_id'),
  },
  (columns) => [
    index('df_pages_rels_order_idx').on(columns.order),
    index('df_pages_rels_parent_idx').on(columns.parent),
    index('df_pages_rels_path_idx').on(columns.path),
    index('df_pages_rels_projects_id_idx').on(columns.projectsID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [df_pages.id],
      name: 'df_pages_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'df_pages_rels_projects_fk',
    }).onDelete('cascade'),
  ],
)

export const projects_gallery = pgTable(
  'projects_gallery',
  {
    _order: integer('_order').notNull(),
    _parentID: integer('_parent_id').notNull(),
    id: varchar('id').primaryKey(),
    image: integer('image_id')
      .notNull()
      .references(() => media.id, {
        onDelete: 'set null',
      }),
  },
  (columns) => [
    index('projects_gallery_order_idx').on(columns._order),
    index('projects_gallery_parent_id_idx').on(columns._parentID),
    index('projects_gallery_image_idx').on(columns.image),
    foreignKey({
      columns: [columns['_parentID']],
      foreignColumns: [projects.id],
      name: 'projects_gallery_parent_id_fk',
    }).onDelete('cascade'),
  ],
)

export const projects = pgTable(
  'projects',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    description: varchar('description'),
    client: varchar('client'),
    location: varchar('location'),
    area: varchar('area'),
    year: numeric('year', { mode: 'number' }),
    category: varchar('category'),
    website: enum_projects_website('website').default('All'),
    status: varchar('status'),
    budget: varchar('budget'),
    featured_archia: boolean('featured_archia').default(false),
    featured_mp: boolean('featured_mp').default(false),
    sort: numeric('sort', { mode: 'number' }),
    seo_page_title: varchar('seo_page_title'),
    seo_meta_description: varchar('seo_meta_description'),
    seo_social_image: integer('seo_social_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    directusId: numeric('directus_id', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('projects_slug_idx').on(columns.slug),
    index('projects_seo_seo_social_image_idx').on(columns.seo_social_image),
    index('projects_updated_at_idx').on(columns.updatedAt),
    index('projects_created_at_idx').on(columns.createdAt),
  ],
)

export const publications = pgTable(
  'publications',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    slug: varchar('slug').notNull(),
    date: timestamp('date', { mode: 'string', withTimezone: true, precision: 3 }),
    latest: boolean('latest').default(false),
    website: enum_publications_website('website').default('Archia'),
    body: varchar('body'),
    coverImage: integer('cover_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    seo_page_title: varchar('seo_page_title'),
    seo_meta_description: varchar('seo_meta_description'),
    seo_social_image: integer('seo_social_image_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    directusId: numeric('directus_id', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex('publications_slug_idx').on(columns.slug),
    index('publications_cover_image_idx').on(columns.coverImage),
    index('publications_seo_seo_social_image_idx').on(columns.seo_social_image),
    index('publications_updated_at_idx').on(columns.updatedAt),
    index('publications_created_at_idx').on(columns.createdAt),
  ],
)

export const members = pgTable(
  'members',
  {
    id: serial('id').primaryKey(),
    name: varchar('name').notNull(),
    role: varchar('role'),
    bio: varchar('bio'),
    photo: integer('photo_id').references(() => media.id, {
      onDelete: 'set null',
    }),
    sort: numeric('sort', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('members_photo_idx').on(columns.photo),
    index('members_updated_at_idx').on(columns.updatedAt),
    index('members_created_at_idx').on(columns.createdAt),
  ],
)

export const contact_info_items = pgTable(
  'contact_info_items',
  {
    id: serial('id').primaryKey(),
    contact_item_1_label: varchar('contact_item_1_label'),
    contact_item_1_content: varchar('contact_item_1_content'),
    contact_item_2_label: varchar('contact_item_2_label'),
    contact_item_2_content: varchar('contact_item_2_content'),
    contact_item_3_label: varchar('contact_item_3_label'),
    contact_item_3_content: varchar('contact_item_3_content'),
    contact_item_4_label: varchar('contact_item_4_label'),
    contact_item_4_content: varchar('contact_item_4_content'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('contact_info_items_updated_at_idx').on(columns.updatedAt),
    index('contact_info_items_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_kv = pgTable(
  'payload_kv',
  {
    id: serial('id').primaryKey(),
    key: varchar('key').notNull(),
    data: jsonb('data').notNull(),
  },
  (columns) => [uniqueIndex('payload_kv_key_idx').on(columns.key)],
)

export const payload_locked_documents = pgTable(
  'payload_locked_documents',
  {
    id: serial('id').primaryKey(),
    globalSlug: varchar('global_slug'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_locked_documents_global_slug_idx').on(columns.globalSlug),
    index('payload_locked_documents_updated_at_idx').on(columns.updatedAt),
    index('payload_locked_documents_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_locked_documents_rels = pgTable(
  'payload_locked_documents_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
    'user-typesID': integer('user_types_id'),
    mediaID: integer('media_id'),
    pagesID: integer('pages_id'),
    'df-pagesID': integer('df_pages_id'),
    projectsID: integer('projects_id'),
    publicationsID: integer('publications_id'),
    membersID: integer('members_id'),
    contact_info_itemsID: integer('contact_info_items_id'),
  },
  (columns) => [
    index('payload_locked_documents_rels_order_idx').on(columns.order),
    index('payload_locked_documents_rels_parent_idx').on(columns.parent),
    index('payload_locked_documents_rels_path_idx').on(columns.path),
    index('payload_locked_documents_rels_users_id_idx').on(columns.usersID),
    index('payload_locked_documents_rels_user_types_id_idx').on(columns['user-typesID']),
    index('payload_locked_documents_rels_media_id_idx').on(columns.mediaID),
    index('payload_locked_documents_rels_pages_id_idx').on(columns.pagesID),
    index('payload_locked_documents_rels_df_pages_id_idx').on(columns['df-pagesID']),
    index('payload_locked_documents_rels_projects_id_idx').on(columns.projectsID),
    index('payload_locked_documents_rels_publications_id_idx').on(columns.publicationsID),
    index('payload_locked_documents_rels_members_id_idx').on(columns.membersID),
    index('payload_locked_documents_rels_contact_info_items_id_idx').on(
      columns.contact_info_itemsID,
    ),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_locked_documents.id],
      name: 'payload_locked_documents_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_locked_documents_rels_users_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['user-typesID']],
      foreignColumns: [user_types.id],
      name: 'payload_locked_documents_rels_user_types_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['mediaID']],
      foreignColumns: [media.id],
      name: 'payload_locked_documents_rels_media_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['pagesID']],
      foreignColumns: [pages.id],
      name: 'payload_locked_documents_rels_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['df-pagesID']],
      foreignColumns: [df_pages.id],
      name: 'payload_locked_documents_rels_df_pages_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['projectsID']],
      foreignColumns: [projects.id],
      name: 'payload_locked_documents_rels_projects_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['publicationsID']],
      foreignColumns: [publications.id],
      name: 'payload_locked_documents_rels_publications_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['membersID']],
      foreignColumns: [members.id],
      name: 'payload_locked_documents_rels_members_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['contact_info_itemsID']],
      foreignColumns: [contact_info_items.id],
      name: 'payload_locked_documents_rels_contact_info_items_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_preferences = pgTable(
  'payload_preferences',
  {
    id: serial('id').primaryKey(),
    key: varchar('key'),
    value: jsonb('value'),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_preferences_key_idx').on(columns.key),
    index('payload_preferences_updated_at_idx').on(columns.updatedAt),
    index('payload_preferences_created_at_idx').on(columns.createdAt),
  ],
)

export const payload_preferences_rels = pgTable(
  'payload_preferences_rels',
  {
    id: serial('id').primaryKey(),
    order: integer('order'),
    parent: integer('parent_id').notNull(),
    path: varchar('path').notNull(),
    usersID: integer('users_id'),
  },
  (columns) => [
    index('payload_preferences_rels_order_idx').on(columns.order),
    index('payload_preferences_rels_parent_idx').on(columns.parent),
    index('payload_preferences_rels_path_idx').on(columns.path),
    index('payload_preferences_rels_users_id_idx').on(columns.usersID),
    foreignKey({
      columns: [columns['parent']],
      foreignColumns: [payload_preferences.id],
      name: 'payload_preferences_rels_parent_fk',
    }).onDelete('cascade'),
    foreignKey({
      columns: [columns['usersID']],
      foreignColumns: [users.id],
      name: 'payload_preferences_rels_users_fk',
    }).onDelete('cascade'),
  ],
)

export const payload_migrations = pgTable(
  'payload_migrations',
  {
    id: serial('id').primaryKey(),
    name: varchar('name'),
    batch: numeric('batch', { mode: 'number' }),
    updatedAt: timestamp('updated_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
    createdAt: timestamp('created_at', { mode: 'string', withTimezone: true, precision: 3 })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index('payload_migrations_updated_at_idx').on(columns.updatedAt),
    index('payload_migrations_created_at_idx').on(columns.createdAt),
  ],
)

export const relations_users_sessions = relations(users_sessions, ({ one }) => ({
  _parentID: one(users, {
    fields: [users_sessions._parentID],
    references: [users.id],
    relationName: 'sessions',
  }),
}))
export const relations_users = relations(users, ({ one, many }) => ({
  customType: one(user_types, {
    fields: [users.customType],
    references: [user_types.id],
    relationName: 'customType',
  }),
  sessions: many(users_sessions, {
    relationName: 'sessions',
  }),
}))
export const relations_user_types = relations(user_types, () => ({}))
export const relations_media = relations(media, () => ({}))
export const relations_pages_blocks_home_hero_video_urls = relations(
  pages_blocks_home_hero_video_urls,
  ({ one }) => ({
    _parentID: one(pages_blocks_home_hero, {
      fields: [pages_blocks_home_hero_video_urls._parentID],
      references: [pages_blocks_home_hero.id],
      relationName: 'videoUrls',
    }),
  }),
)
export const relations_pages_blocks_home_hero = relations(
  pages_blocks_home_hero,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_home_hero._parentID],
      references: [pages.id],
      relationName: '_blocks_homeHero',
    }),
    videoUrls: many(pages_blocks_home_hero_video_urls, {
      relationName: 'videoUrls',
    }),
  }),
)
export const relations_pages_blocks_featured_projects = relations(
  pages_blocks_featured_projects,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_featured_projects._parentID],
      references: [pages.id],
      relationName: '_blocks_featuredProjects',
    }),
  }),
)
export const relations_pages_blocks_projects_archive = relations(
  pages_blocks_projects_archive,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_projects_archive._parentID],
      references: [pages.id],
      relationName: '_blocks_projectsArchive',
    }),
  }),
)
export const relations_pages_blocks_studio_intro = relations(
  pages_blocks_studio_intro,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_studio_intro._parentID],
      references: [pages.id],
      relationName: '_blocks_studioIntro',
    }),
    heroImage: one(media, {
      fields: [pages_blocks_studio_intro.heroImage],
      references: [media.id],
      relationName: 'heroImage',
    }),
  }),
)
export const relations_pages_blocks_founder_profile = relations(
  pages_blocks_founder_profile,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_founder_profile._parentID],
      references: [pages.id],
      relationName: '_blocks_founderProfile',
    }),
    portrait: one(media, {
      fields: [pages_blocks_founder_profile.portrait],
      references: [media.id],
      relationName: 'portrait',
    }),
  }),
)
export const relations_pages_blocks_about_section = relations(
  pages_blocks_about_section,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_about_section._parentID],
      references: [pages.id],
      relationName: '_blocks_aboutSection',
    }),
  }),
)
export const relations_pages_blocks_studio_pillars_pillars = relations(
  pages_blocks_studio_pillars_pillars,
  ({ one }) => ({
    _parentID: one(pages_blocks_studio_pillars, {
      fields: [pages_blocks_studio_pillars_pillars._parentID],
      references: [pages_blocks_studio_pillars.id],
      relationName: 'pillars',
    }),
  }),
)
export const relations_pages_blocks_studio_pillars = relations(
  pages_blocks_studio_pillars,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_studio_pillars._parentID],
      references: [pages.id],
      relationName: '_blocks_studioPillars',
    }),
    pillars: many(pages_blocks_studio_pillars_pillars, {
      relationName: 'pillars',
    }),
  }),
)
export const relations_pages_blocks_journal_feed = relations(
  pages_blocks_journal_feed,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_journal_feed._parentID],
      references: [pages.id],
      relationName: '_blocks_journalFeed',
    }),
  }),
)
export const relations_pages_blocks_journal_archive = relations(
  pages_blocks_journal_archive,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_journal_archive._parentID],
      references: [pages.id],
      relationName: '_blocks_journalArchive',
    }),
  }),
)
export const relations_pages_blocks_contact_hero = relations(
  pages_blocks_contact_hero,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_contact_hero._parentID],
      references: [pages.id],
      relationName: '_blocks_contactHero',
    }),
  }),
)
export const relations_pages_blocks_contact_locations_locations = relations(
  pages_blocks_contact_locations_locations,
  ({ one }) => ({
    _parentID: one(pages_blocks_contact_locations, {
      fields: [pages_blocks_contact_locations_locations._parentID],
      references: [pages_blocks_contact_locations.id],
      relationName: 'locations',
    }),
  }),
)
export const relations_pages_blocks_contact_locations = relations(
  pages_blocks_contact_locations,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_contact_locations._parentID],
      references: [pages.id],
      relationName: '_blocks_contactLocations',
    }),
    locations: many(pages_blocks_contact_locations_locations, {
      relationName: 'locations',
    }),
  }),
)
export const relations_pages_blocks_full_width_media = relations(
  pages_blocks_full_width_media,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_full_width_media._parentID],
      references: [pages.id],
      relationName: '_blocks_fullWidthMedia',
    }),
    image: one(media, {
      fields: [pages_blocks_full_width_media.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_pages_blocks_content_block = relations(
  pages_blocks_content_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_content_block._parentID],
      references: [pages.id],
      relationName: '_blocks_contentBlock',
    }),
  }),
)
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: '_rels',
  }),
  projectsID: one(projects, {
    fields: [pages_rels.projectsID],
    references: [projects.id],
    relationName: 'projects',
  }),
  publicationsID: one(publications, {
    fields: [pages_rels.publicationsID],
    references: [publications.id],
    relationName: 'publications',
  }),
}))
export const relations_pages = relations(pages, ({ many }) => ({
  _blocks_homeHero: many(pages_blocks_home_hero, {
    relationName: '_blocks_homeHero',
  }),
  _blocks_featuredProjects: many(pages_blocks_featured_projects, {
    relationName: '_blocks_featuredProjects',
  }),
  _blocks_projectsArchive: many(pages_blocks_projects_archive, {
    relationName: '_blocks_projectsArchive',
  }),
  _blocks_studioIntro: many(pages_blocks_studio_intro, {
    relationName: '_blocks_studioIntro',
  }),
  _blocks_founderProfile: many(pages_blocks_founder_profile, {
    relationName: '_blocks_founderProfile',
  }),
  _blocks_aboutSection: many(pages_blocks_about_section, {
    relationName: '_blocks_aboutSection',
  }),
  _blocks_studioPillars: many(pages_blocks_studio_pillars, {
    relationName: '_blocks_studioPillars',
  }),
  _blocks_journalFeed: many(pages_blocks_journal_feed, {
    relationName: '_blocks_journalFeed',
  }),
  _blocks_journalArchive: many(pages_blocks_journal_archive, {
    relationName: '_blocks_journalArchive',
  }),
  _blocks_contactHero: many(pages_blocks_contact_hero, {
    relationName: '_blocks_contactHero',
  }),
  _blocks_contactLocations: many(pages_blocks_contact_locations, {
    relationName: '_blocks_contactLocations',
  }),
  _blocks_fullWidthMedia: many(pages_blocks_full_width_media, {
    relationName: '_blocks_fullWidthMedia',
  }),
  _blocks_contentBlock: many(pages_blocks_content_block, {
    relationName: '_blocks_contentBlock',
  }),
  _rels: many(pages_rels, {
    relationName: '_rels',
  }),
}))
export const relations_df_pages_blocks_df_biography = relations(
  df_pages_blocks_df_biography,
  ({ one }) => ({
    _parentID: one(df_pages, {
      fields: [df_pages_blocks_df_biography._parentID],
      references: [df_pages.id],
      relationName: '_blocks_dfBiography',
    }),
    portrait: one(media, {
      fields: [df_pages_blocks_df_biography.portrait],
      references: [media.id],
      relationName: 'portrait',
    }),
  }),
)
export const relations_df_pages_blocks_df_projects = relations(
  df_pages_blocks_df_projects,
  ({ one }) => ({
    _parentID: one(df_pages, {
      fields: [df_pages_blocks_df_projects._parentID],
      references: [df_pages.id],
      relationName: '_blocks_dfProjects',
    }),
  }),
)
export const relations_df_pages_blocks_df_media = relations(
  df_pages_blocks_df_media,
  ({ one }) => ({
    _parentID: one(df_pages, {
      fields: [df_pages_blocks_df_media._parentID],
      references: [df_pages.id],
      relationName: '_blocks_dfMedia',
    }),
    image: one(media, {
      fields: [df_pages_blocks_df_media.image],
      references: [media.id],
      relationName: 'image',
    }),
  }),
)
export const relations_df_pages_blocks_df_content = relations(
  df_pages_blocks_df_content,
  ({ one }) => ({
    _parentID: one(df_pages, {
      fields: [df_pages_blocks_df_content._parentID],
      references: [df_pages.id],
      relationName: '_blocks_dfContent',
    }),
  }),
)
export const relations_df_pages_blocks_df_contact = relations(
  df_pages_blocks_df_contact,
  ({ one }) => ({
    _parentID: one(df_pages, {
      fields: [df_pages_blocks_df_contact._parentID],
      references: [df_pages.id],
      relationName: '_blocks_dfContact',
    }),
  }),
)
export const relations_df_pages_rels = relations(df_pages_rels, ({ one }) => ({
  parent: one(df_pages, {
    fields: [df_pages_rels.parent],
    references: [df_pages.id],
    relationName: '_rels',
  }),
  projectsID: one(projects, {
    fields: [df_pages_rels.projectsID],
    references: [projects.id],
    relationName: 'projects',
  }),
}))
export const relations_df_pages = relations(df_pages, ({ many }) => ({
  _blocks_dfBiography: many(df_pages_blocks_df_biography, {
    relationName: '_blocks_dfBiography',
  }),
  _blocks_dfProjects: many(df_pages_blocks_df_projects, {
    relationName: '_blocks_dfProjects',
  }),
  _blocks_dfMedia: many(df_pages_blocks_df_media, {
    relationName: '_blocks_dfMedia',
  }),
  _blocks_dfContent: many(df_pages_blocks_df_content, {
    relationName: '_blocks_dfContent',
  }),
  _blocks_dfContact: many(df_pages_blocks_df_contact, {
    relationName: '_blocks_dfContact',
  }),
  _rels: many(df_pages_rels, {
    relationName: '_rels',
  }),
}))
export const relations_projects_gallery = relations(projects_gallery, ({ one }) => ({
  _parentID: one(projects, {
    fields: [projects_gallery._parentID],
    references: [projects.id],
    relationName: 'gallery',
  }),
  image: one(media, {
    fields: [projects_gallery.image],
    references: [media.id],
    relationName: 'image',
  }),
}))
export const relations_projects = relations(projects, ({ one, many }) => ({
  gallery: many(projects_gallery, {
    relationName: 'gallery',
  }),
  seo_social_image: one(media, {
    fields: [projects.seo_social_image],
    references: [media.id],
    relationName: 'seo_social_image',
  }),
}))
export const relations_publications = relations(publications, ({ one }) => ({
  coverImage: one(media, {
    fields: [publications.coverImage],
    references: [media.id],
    relationName: 'coverImage',
  }),
  seo_social_image: one(media, {
    fields: [publications.seo_social_image],
    references: [media.id],
    relationName: 'seo_social_image',
  }),
}))
export const relations_members = relations(members, ({ one }) => ({
  photo: one(media, {
    fields: [members.photo],
    references: [media.id],
    relationName: 'photo',
  }),
}))
export const relations_contact_info_items = relations(contact_info_items, () => ({}))
export const relations_payload_kv = relations(payload_kv, () => ({}))
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
    'user-typesID': one(user_types, {
      fields: [payload_locked_documents_rels['user-typesID']],
      references: [user_types.id],
      relationName: 'user-types',
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: 'media',
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: 'pages',
    }),
    'df-pagesID': one(df_pages, {
      fields: [payload_locked_documents_rels['df-pagesID']],
      references: [df_pages.id],
      relationName: 'df-pages',
    }),
    projectsID: one(projects, {
      fields: [payload_locked_documents_rels.projectsID],
      references: [projects.id],
      relationName: 'projects',
    }),
    publicationsID: one(publications, {
      fields: [payload_locked_documents_rels.publicationsID],
      references: [publications.id],
      relationName: 'publications',
    }),
    membersID: one(members, {
      fields: [payload_locked_documents_rels.membersID],
      references: [members.id],
      relationName: 'members',
    }),
    contact_info_itemsID: one(contact_info_items, {
      fields: [payload_locked_documents_rels.contact_info_itemsID],
      references: [contact_info_items.id],
      relationName: 'contact_info_items',
    }),
  }),
)
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: '_rels',
    }),
  }),
)
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: '_rels',
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: 'users',
    }),
  }),
)
export const relations_payload_preferences = relations(payload_preferences, ({ many }) => ({
  _rels: many(payload_preferences_rels, {
    relationName: '_rels',
  }),
}))
export const relations_payload_migrations = relations(payload_migrations, () => ({}))

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role
  enum_df_pages_blocks_df_media_type: typeof enum_df_pages_blocks_df_media_type
  enum_projects_website: typeof enum_projects_website
  enum_publications_website: typeof enum_publications_website
  users_sessions: typeof users_sessions
  users: typeof users
  user_types: typeof user_types
  media: typeof media
  pages_blocks_home_hero_video_urls: typeof pages_blocks_home_hero_video_urls
  pages_blocks_home_hero: typeof pages_blocks_home_hero
  pages_blocks_featured_projects: typeof pages_blocks_featured_projects
  pages_blocks_projects_archive: typeof pages_blocks_projects_archive
  pages_blocks_studio_intro: typeof pages_blocks_studio_intro
  pages_blocks_founder_profile: typeof pages_blocks_founder_profile
  pages_blocks_about_section: typeof pages_blocks_about_section
  pages_blocks_studio_pillars_pillars: typeof pages_blocks_studio_pillars_pillars
  pages_blocks_studio_pillars: typeof pages_blocks_studio_pillars
  pages_blocks_journal_feed: typeof pages_blocks_journal_feed
  pages_blocks_journal_archive: typeof pages_blocks_journal_archive
  pages_blocks_contact_hero: typeof pages_blocks_contact_hero
  pages_blocks_contact_locations_locations: typeof pages_blocks_contact_locations_locations
  pages_blocks_contact_locations: typeof pages_blocks_contact_locations
  pages_blocks_full_width_media: typeof pages_blocks_full_width_media
  pages_blocks_content_block: typeof pages_blocks_content_block
  pages: typeof pages
  pages_rels: typeof pages_rels
  df_pages_blocks_df_biography: typeof df_pages_blocks_df_biography
  df_pages_blocks_df_projects: typeof df_pages_blocks_df_projects
  df_pages_blocks_df_media: typeof df_pages_blocks_df_media
  df_pages_blocks_df_content: typeof df_pages_blocks_df_content
  df_pages_blocks_df_contact: typeof df_pages_blocks_df_contact
  df_pages: typeof df_pages
  df_pages_rels: typeof df_pages_rels
  projects_gallery: typeof projects_gallery
  projects: typeof projects
  publications: typeof publications
  members: typeof members
  contact_info_items: typeof contact_info_items
  payload_kv: typeof payload_kv
  payload_locked_documents: typeof payload_locked_documents
  payload_locked_documents_rels: typeof payload_locked_documents_rels
  payload_preferences: typeof payload_preferences
  payload_preferences_rels: typeof payload_preferences_rels
  payload_migrations: typeof payload_migrations
  relations_users_sessions: typeof relations_users_sessions
  relations_users: typeof relations_users
  relations_user_types: typeof relations_user_types
  relations_media: typeof relations_media
  relations_pages_blocks_home_hero_video_urls: typeof relations_pages_blocks_home_hero_video_urls
  relations_pages_blocks_home_hero: typeof relations_pages_blocks_home_hero
  relations_pages_blocks_featured_projects: typeof relations_pages_blocks_featured_projects
  relations_pages_blocks_projects_archive: typeof relations_pages_blocks_projects_archive
  relations_pages_blocks_studio_intro: typeof relations_pages_blocks_studio_intro
  relations_pages_blocks_founder_profile: typeof relations_pages_blocks_founder_profile
  relations_pages_blocks_about_section: typeof relations_pages_blocks_about_section
  relations_pages_blocks_studio_pillars_pillars: typeof relations_pages_blocks_studio_pillars_pillars
  relations_pages_blocks_studio_pillars: typeof relations_pages_blocks_studio_pillars
  relations_pages_blocks_journal_feed: typeof relations_pages_blocks_journal_feed
  relations_pages_blocks_journal_archive: typeof relations_pages_blocks_journal_archive
  relations_pages_blocks_contact_hero: typeof relations_pages_blocks_contact_hero
  relations_pages_blocks_contact_locations_locations: typeof relations_pages_blocks_contact_locations_locations
  relations_pages_blocks_contact_locations: typeof relations_pages_blocks_contact_locations
  relations_pages_blocks_full_width_media: typeof relations_pages_blocks_full_width_media
  relations_pages_blocks_content_block: typeof relations_pages_blocks_content_block
  relations_pages_rels: typeof relations_pages_rels
  relations_pages: typeof relations_pages
  relations_df_pages_blocks_df_biography: typeof relations_df_pages_blocks_df_biography
  relations_df_pages_blocks_df_projects: typeof relations_df_pages_blocks_df_projects
  relations_df_pages_blocks_df_media: typeof relations_df_pages_blocks_df_media
  relations_df_pages_blocks_df_content: typeof relations_df_pages_blocks_df_content
  relations_df_pages_blocks_df_contact: typeof relations_df_pages_blocks_df_contact
  relations_df_pages_rels: typeof relations_df_pages_rels
  relations_df_pages: typeof relations_df_pages
  relations_projects_gallery: typeof relations_projects_gallery
  relations_projects: typeof relations_projects
  relations_publications: typeof relations_publications
  relations_members: typeof relations_members
  relations_contact_info_items: typeof relations_contact_info_items
  relations_payload_kv: typeof relations_payload_kv
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels
  relations_payload_locked_documents: typeof relations_payload_locked_documents
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels
  relations_payload_preferences: typeof relations_payload_preferences
  relations_payload_migrations: typeof relations_payload_migrations
}

declare module '@payloadcms/db-postgres' {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema
  }
}
