/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    projects: Project;
    publications: Publication;
    'df-pages': DfPage;
    'df-projects': DfProject;
    'df-publications': DfPublication;
    media: Media;
    members: Member;
    contact_info_items: ContactInfoItem;
    users: User;
    'user-types': UserType;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    'df-pages': DfPagesSelect<false> | DfPagesSelect<true>;
    'df-projects': DfProjectsSelect<false> | DfProjectsSelect<true>;
    'df-publications': DfPublicationsSelect<false> | DfPublicationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    contact_info_items: ContactInfoItemsSelect<false> | ContactInfoItemsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'user-types': UserTypesSelect<false> | UserTypesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  layout: (
    | {
        headline?: string | null;
        subtitle?: string | null;
        videoUrls?:
          | {
              url: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'homeHero';
      }
    | {
        tag?: string | null;
        title?: string | null;
        projects?: (number | Project)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featuredProjects';
      }
    | {
        /**
         * Headline displayed at the top of the projects directory
         */
        title?: string | null;
        /**
         * Portfolio overview. Automatically lists all 20 projects with interactive category filters.
         */
        description?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'projectsArchive';
      }
    | {
        title?: string | null;
        badge?: string | null;
        description?: string | null;
        heroImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'studioIntro';
      }
    | {
        name?: string | null;
        role?: string | null;
        portrait?: (number | null) | Media;
        portraitCaption?: string | null;
        bio?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'founderProfile';
      }
    | {
        title?: string | null;
        description?: string | null;
        subtext?: string | null;
        ctaLabel?: string | null;
        ctaLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'aboutSection';
      }
    | {
        pillars?:
          | {
              number?: string | null;
              title?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'studioPillars';
      }
    | {
        tag?: string | null;
        title?: string | null;
        articles?: (number | Publication)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'journalFeed';
      }
    | {
        /**
         * Headline displayed at the top of the publications directory
         */
        title?: string | null;
        /**
         * Editorial overview. Automatically lists all 20 publications with interactive category filters.
         */
        description?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'journalArchive';
      }
    | {
        title?: string | null;
        description?: string | null;
        email?: string | null;
        statusText?: string | null;
        mapLink?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactHero';
      }
    | {
        locations?:
          | {
              tag?: string | null;
              studioName?: string | null;
              address?: string | null;
              hours?: string | null;
              transit?: string | null;
              mapUrl?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactLocations';
      }
    | {
        image?: (number | null) | Media;
        caption?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'fullWidthMedia';
      }
    | {
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentBlock';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  slug: string;
  website?: ('None' | 'Archia' | 'Magnum Projects' | 'DF' | 'All') | null;
  description?: string | null;
  client?: string | null;
  location?: string | null;
  area?: string | null;
  year?: number | null;
  category?: string | null;
  status?: string | null;
  budget?: string | null;
  featured_archia?: boolean | null;
  featured_mp?: boolean | null;
  sort?: number | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  seo?: {
    /**
     * Ideal length 45-60 characters recommended.
     */
    page_title?: string | null;
    /**
     * Ideal length 130-160 characters recommended.
     */
    meta_description?: string | null;
    social_image?: (number | null) | Media;
  };
  directusId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  name: string;
  slug: string;
  website?: ('None' | 'Archia' | 'Magnum Projects' | 'DF' | 'All') | null;
  date?: string | null;
  latest?: boolean | null;
  /**
   * Article content / HTML markup
   */
  body?: string | null;
  coverImage?: (number | null) | Media;
  seo?: {
    /**
     * Ideal length 45-60 characters recommended.
     */
    page_title?: string | null;
    /**
     * Ideal length 130-160 characters recommended.
     */
    meta_description?: string | null;
    social_image?: (number | null) | Media;
  };
  directusId?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Davud Farzulla website sections (automatically populated).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "df-pages".
 */
export interface DfPage {
  id: number;
  title: string;
  tagline?: string | null;
  categoryFilter?: ('Interior' | 'Architecture' | 'All') | null;
  typologyFilter?: ('Residential' | 'Hospitality' | 'Offices' | 'All') | null;
  description?: string | null;
  heroImage?: (number | null) | Media;
  slug: string;
  contentSource?: ('projects' | 'news' | 'info') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Davud Farzulla architecture & interior design projects.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "df-projects".
 */
export interface DfProject {
  id: number;
  name: string;
  slug: string;
  website?: ('None' | 'Archia' | 'Magnum Projects' | 'DF' | 'All') | null;
  description?: string | null;
  client?: string | null;
  location?: string | null;
  area?: string | null;
  year?: number | null;
  category?: ('Interior' | 'Architecture' | 'Product') | null;
  typology?: ('Residential' | 'Hospitality' | 'Offices' | 'Retail' | 'Other') | null;
  coverImage?: (number | null) | Media;
  gallery?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Davud Farzulla news, press features, and monograph publications.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "df-publications".
 */
export interface DfPublication {
  id: number;
  name: string;
  slug: string;
  website?: ('None' | 'Archia' | 'Magnum Projects' | 'DF' | 'All') | null;
  date?: string | null;
  latest?: boolean | null;
  subtitle?: string | null;
  body?: string | null;
  coverImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_info_items".
 */
export interface ContactInfoItem {
  id: number;
  contact_item_1_label?: string | null;
  contact_item_1_content?: string | null;
  contact_item_2_label?: string | null;
  contact_item_2_content?: string | null;
  contact_item_3_label?: string | null;
  contact_item_3_content?: string | null;
  contact_item_4_label?: string | null;
  contact_item_4_content?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'moderator' | 'custom';
  /**
   * Select the custom role with customized permissions
   */
  customType?: (number | null) | UserType;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Create custom roles and manage granular permissions for studio team members.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-types".
 */
export interface UserType {
  id: number;
  title: string;
  /**
   * Unique identifier, e.g. copywriter, project-reviewer
   */
  slug: string;
  description?: string | null;
  permissions?: {
    managePages?: boolean | null;
    manageProjects?: boolean | null;
    managePublications?: boolean | null;
    manageMedia?: boolean | null;
    manageStudio?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'df-pages';
        value: number | DfPage;
      } | null)
    | ({
        relationTo: 'df-projects';
        value: number | DfProject;
      } | null)
    | ({
        relationTo: 'df-publications';
        value: number | DfPublication;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'contact_info_items';
        value: number | ContactInfoItem;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'user-types';
        value: number | UserType;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        homeHero?:
          | T
          | {
              headline?: T;
              subtitle?: T;
              videoUrls?:
                | T
                | {
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featuredProjects?:
          | T
          | {
              tag?: T;
              title?: T;
              projects?: T;
              id?: T;
              blockName?: T;
            };
        projectsArchive?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        studioIntro?:
          | T
          | {
              title?: T;
              badge?: T;
              description?: T;
              heroImage?: T;
              id?: T;
              blockName?: T;
            };
        founderProfile?:
          | T
          | {
              name?: T;
              role?: T;
              portrait?: T;
              portraitCaption?: T;
              bio?: T;
              id?: T;
              blockName?: T;
            };
        aboutSection?:
          | T
          | {
              title?: T;
              description?: T;
              subtext?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        studioPillars?:
          | T
          | {
              pillars?:
                | T
                | {
                    number?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        journalFeed?:
          | T
          | {
              tag?: T;
              title?: T;
              articles?: T;
              id?: T;
              blockName?: T;
            };
        journalArchive?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        contactHero?:
          | T
          | {
              title?: T;
              description?: T;
              email?: T;
              statusText?: T;
              mapLink?: T;
              id?: T;
              blockName?: T;
            };
        contactLocations?:
          | T
          | {
              locations?:
                | T
                | {
                    tag?: T;
                    studioName?: T;
                    address?: T;
                    hours?: T;
                    transit?: T;
                    mapUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        fullWidthMedia?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        contentBlock?:
          | T
          | {
              richText?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  website?: T;
  description?: T;
  client?: T;
  location?: T;
  area?: T;
  year?: T;
  category?: T;
  status?: T;
  budget?: T;
  featured_archia?: T;
  featured_mp?: T;
  sort?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        page_title?: T;
        meta_description?: T;
        social_image?: T;
      };
  directusId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  website?: T;
  date?: T;
  latest?: T;
  body?: T;
  coverImage?: T;
  seo?:
    | T
    | {
        page_title?: T;
        meta_description?: T;
        social_image?: T;
      };
  directusId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "df-pages_select".
 */
export interface DfPagesSelect<T extends boolean = true> {
  title?: T;
  tagline?: T;
  categoryFilter?: T;
  typologyFilter?: T;
  description?: T;
  heroImage?: T;
  slug?: T;
  contentSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "df-projects_select".
 */
export interface DfProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  website?: T;
  description?: T;
  client?: T;
  location?: T;
  area?: T;
  year?: T;
  category?: T;
  typology?: T;
  coverImage?: T;
  gallery?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "df-publications_select".
 */
export interface DfPublicationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  website?: T;
  date?: T;
  latest?: T;
  subtitle?: T;
  body?: T;
  coverImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact_info_items_select".
 */
export interface ContactInfoItemsSelect<T extends boolean = true> {
  contact_item_1_label?: T;
  contact_item_1_content?: T;
  contact_item_2_label?: T;
  contact_item_2_content?: T;
  contact_item_3_label?: T;
  contact_item_3_content?: T;
  contact_item_4_label?: T;
  contact_item_4_content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  customType?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "user-types_select".
 */
export interface UserTypesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  permissions?:
    | T
    | {
        managePages?: T;
        manageProjects?: T;
        managePublications?: T;
        manageMedia?: T;
        manageStudio?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}